### ISSUE TITLE
Error when load world

### ISSUE THREAD

**Issue by Porama6400** [SirCmpwn/Craft.Net#234]
I got this error when load world

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Craft.Net.Anvil
  StackTrace:
       at Craft.Net.Anvil.Level.Load(String file)
       at Craft.Net.Anvil.Level.LoadFrom(String directory)
       at Craft.Net.Anvil.Level.LoadSavedLevel(String world)
       at ConsoleTester.Program.Main(String[] args) in c:\users\fujitsu\documents\visual studio 2015\Projects\TestCraftNet\ConsoleTester\Program.cs:line 15
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

How can i fix this?

**Comment by Porama6400** [comment]
Program.cs:15

Level l = Level.LoadSavedLevel("C:\Users\Fujitsu\Desktop\SPG\world");
